### ISSUE TITLE
[FEATURE] rejudge submissions

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [jdabtieu/CTFOJ#82]
## Is your feature request related to a problem? Please describe.
Right now we can't rejudge submissions.

## Describe the solution you'd like
Rejudge submissions button.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by jdabtieu** [comment]
This would require us to first store submissions. We currently don't do that but it should be trivial enough.

I'll deal with it.

**Comment by jdabtieu** [comment]
I'm going to deal with this in the next update. The current update that's being worked on right now already has a boatload of new features and adding this feature would require a database update

**Comment by jdabtieu** [comment]
- [ ] Filter flag submissions
    - [ ] Ensure all flags fit the format `[ -~]{1, 1024}`
    - [ ] Block flag submissions that do not fit the flag format
- [ ] Store submitted flags in database
- [ ] Allow rejudging


Filtering flag submissions is to prevent entries like `�¢)h>)h>)h>)h>)h>)h>)h>)h>)h0¢)h)h)h)h)h)h)h¢)h)h)h)h)h)h)hw&öær6öFRâFR&&&BF2G2VB&6²çFòFRBà¢)h)h)h)h)h)h)h`

**Comment by jdabtieu** [comment]
@slightlyskepticalpotat how should we implement rejudging? I don't think it's useful to rejudge individual solutions (unlike on DMOJ where code between submissions can be different) since your submitted flag is either correct or incorrect, period.

I think perhaps when editing a problem's flag there should be a checkbox called 'Rejudge existing submissions?', and the behaviour should be like this:
If unticked, keep existing submissions intact and only enforce the new flag on new submissions
If ticked, rejudge all existing submissions to this problem to use the new flag and enforce the new flag on new submissions

**Comment by jdabtieu** [comment]
Current status: Since 0aba42b, the application is capable & does store submissions in the database. Rejudging and viewing flag submissions can be added in the next version without any database changes.

**Comment by slightlyskepticalpotat** [comment]
Yeah, I agree that the edit problems page should have that box. If there were technical issues, admins can also edit the same flag  but still check the box for rejudging
